site_name: P-SAMS
site_url: https://p-sams.carringtonlab.org
site_description: "P-SAMS: The Plant Small RNA Maker Suite"
site_author: "Carrington Lab"
repo_url: https://github.com/carringtonlab/p-sams
copyright: "Copyright 2024, Donald Danforth Plant Science Center"
theme:
 name: bootstrap4
 next_previous: false

plugins:
  - bootstrap4-blockquotes
  - bootstrap4-tables

nav:
  - Home: index.md
  - "FAQ": faq.md
